# Generated by Django 6.0.1 on 2026-01-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='perfil_fotos/default.png', null=True, upload_to='perfil_fotos/'),
        ),
    ]
