# Generated by Django 6.0.1 on 2026-01-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_fotos/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='plano_ativo',
            field=models.CharField(default='premium', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='prompts_restantes',
            field=models.IntegerField(default=9999),
        ),
    ]
