"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Carrega as variáveis do .env
load_dotenv()

# Agora podes usar as variáveis em qualquer parte do projeto
PAYSUITE_API_KEY = os.getenv('PAYSUITE_API_KEY')
PAYSUITE_ID = os.getenv('PAYSUITE_ID')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
VIP_USERS_STR = os.getenv('VIP_USERS', '')
VIP_USERS = [user.strip() for user in VIP_USERS_STR.split(',') if user.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Definição da SECRET_KEY vinda do .env
SECRET_KEY = os.getenv('SECRET_KEY')

# Configuração de DEBUG (converte a string do .env para Booleano)
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Se quiser testar se ele está a ler, adicione esta linha temporária:
if not SECRET_KEY:
    raise ValueError("O Django não conseguiu ler a SECRET_KEY do ficheiro .env")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Seus Apps
    'users',
    'chat',
    'pagamentos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Adicione esta linha
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

AUTH_USER_MODEL = 'users.Usuario'

# Configuração de fuso horário para Moçambique (importante para o reset de prompts)
TIME_ZONE = 'Africa/Maputo'
USE_TZ = True

LANGUAGE_CODE = 'pt-br'

USE_I18N = True

# core/settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Redireciona para a nossa URL personalizada em vez de /accounts/login/
LOGIN_URL = 'login'

# Para onde o usuário vai depois de logar (Raiz / Chat)
LOGIN_REDIRECT_URL = 'chat_index'

# Para onde o usuário vai depois de sair
LOGOUT_REDIRECT_URL = 'login'
# Esta linha abaixo é necessária se estiveres a usar Django 5.0+ 
# para permitir sair via link (GET) em vez de apenas POST
LOGOUT_ON_GET = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
